module.exports = {
  caseType:'human_reviewed_sales_training_outcome',
  initialState:'goal_registered',
  states:['goal_registered','consent_verified','work_item_assigned','simulation_recorded','evaluation_recorded','coach_review','learner_feedback','outcome_approved','appeal_open','corrected','deletion_verified','closed'],
  createRoles:['coach','training_manager'],
  assessmentRoles:['coach','assessment_reviewer','training_manager'],
  auditRoles:['training_manager','privacy_reviewer','auditor'],
  connectorRoles:['integration_operator','training_manager'],
  evidenceKinds:['role_goal_version','learner_consent','cohort_manifest','assessment_version','content_version','simulation_digest','evaluation_report','bias_report','accessibility_report','progression_report','coach_review','learner_feedback','appeal_record','correction_record','outcome_record','deletion_receipt'],
  requiredSignals:['roleVersion','goalVersion','assessmentVersion','contentVersion','policyVersion','rightsStatus','consentStatus','validityScore','biasGap','accessibilityScore','progressionScore','outcomeImprovement','deletionStatus'],
  professionalBoundary:'Simulation scores support coaching only. Human coaches and learners review outcomes; no employment, compensation, promotion, or disciplinary decision is automated.',
  connectors:[
    {name:'lms',purpose:'course, assignment, and completion receipts'},
    {name:'hris',purpose:'minimal role and consent versions'},
    {name:'ats',purpose:'quarantined training-context receipts only'},
    {name:'calendar',purpose:'consented session receipts'},
    {name:'content_repository',purpose:'versioned collateral and license manifests'},
    {name:'communications',purpose:'consented coaching notifications'},
    {name:'analytics',purpose:'aggregated validity and outcome receipts'},
  ],
  transitions:[
    {from:'goal_registered',action:'verify_consent',to:'consent_verified',roles:['coach','privacy_reviewer'],requiresEvidence:true},
    {from:'consent_verified',action:'assign_work_item',to:'work_item_assigned',roles:['coach','training_manager'],requiresEvidence:true},
    {from:'work_item_assigned',action:'record_simulation',to:'simulation_recorded',roles:['coach','integration_operator'],requiresEvidence:true},
    {from:'simulation_recorded',action:'record_evaluation',to:'evaluation_recorded',roles:['assessment_reviewer'],requiresEvidence:true,dualControl:true},
    {from:'evaluation_recorded',action:'submit_coach_review',to:'coach_review',roles:['coach'],requiresEvidence:true,dualControl:true},
    {from:'coach_review',action:'record_learner_feedback',to:'learner_feedback',roles:['coach','training_manager'],requiresEvidence:true,dualControl:true},
    {from:'learner_feedback',action:'approve_outcome',to:'outcome_approved',roles:['training_manager'],requiresEvidence:true,dualControl:true},
    {from:'outcome_approved',action:'open_appeal',to:'appeal_open',roles:['coach','training_manager'],requiresEvidence:true},
    {from:'appeal_open',action:'record_correction',to:'corrected',roles:['assessment_reviewer','training_manager'],requiresEvidence:true,dualControl:true},
    {from:'outcome_approved',action:'verify_deletion',to:'deletion_verified',roles:['privacy_reviewer','integration_operator'],requiresEvidence:true,dualControl:true},
    {from:'corrected',action:'close_outcome',to:'closed',roles:['training_manager'],requiresEvidence:true},
    {from:'deletion_verified',action:'close_outcome',to:'closed',roles:['training_manager'],requiresEvidence:true},
  ],
  acceptedFixture:{roleVersion:'r1',goalVersion:'g1',assessmentVersion:'a1',contentVersion:'c1',policyVersion:'p1',rightsStatus:'verified',consentStatus:'verified',validityScore:0.92,biasGap:0.03,accessibilityScore:0.98,progressionScore:0.85,outcomeImprovement:0.12,deletionStatus:'scheduled'},
  rejectedFixture:{roleVersion:'r1',goalVersion:'g1',assessmentVersion:'a1',contentVersion:'c1',policyVersion:'p1',rightsStatus:'verified',consentStatus:'verified',validityScore:0.92,biasGap:0.2,accessibilityScore:0.98,progressionScore:0.85,outcomeImprovement:0.12,deletionStatus:'scheduled'},
  readyDisposition:'coach_and_learner_review_required',
  holdDisposition:'validity_bias_accessibility_or_consent_hold',
  decisionField:'employmentDecision',
  assess:(x)=>{const validity=Number(x.validityScore),bias=Number(x.biasGap),accessibility=Number(x.accessibilityScore),progression=Number(x.progressionScore),improvement=Number(x.outcomeImprovement);const ready=x.rightsStatus==='verified'&&x.consentStatus==='verified'&&validity>=0.9&&bias<=0.05&&accessibility>=0.95&&progression>=0.8&&improvement>=0&&['scheduled','verified'].includes(x.deletionStatus);return{disposition:ready?'coach_and_learner_review_required':'validity_bias_accessibility_or_consent_hold',employmentDecision:null,metrics:{validity,biasGap:bias,accessibility,progression,improvement},versions:{role:x.roleVersion,goal:x.goalVersion,assessment:x.assessmentVersion,content:x.contentVersion}};},
};
