const { sequelize, User, SalesScenario, RolePlaySession, Objection, PitchPractice, Playbook,
  PerformanceMetric, ProductKnowledge, CoachingPlan, CallScript, EmailTemplate,
  DealSimulation, BuyerPersona, BattleCard, TrainingModule, NegotiationTactic, LeaderboardEntry
} = require('../models');
const bcrypt = require('bcryptjs');

async function seed() {
  try {
    await sequelize.sync({ force: true });
    console.log('Database synced.');

    // Users
    const hash = await bcrypt.hash('password123', 10);
    const users = await User.bulkCreate([
      { name: 'John Mitchell', email: 'john@salesteam.com', password: hash, role: 'admin', avatar: 'JM' },
      { name: 'Sarah Chen', email: 'sarah@salesteam.com', password: hash, role: 'manager', avatar: 'SC' },
      { name: 'Mike Johnson', email: 'mike@salesteam.com', password: hash, role: 'rep', avatar: 'MJ' },
      { name: 'Emily Davis', email: 'emily@salesteam.com', password: hash, role: 'rep', avatar: 'ED' },
      { name: 'Demo User', email: 'demo@demo.com', password: hash, role: 'admin', avatar: 'DU' }
    ]);

    // 1. Sales Scenarios (15)
    await SalesScenario.bulkCreate([
      { title: 'Enterprise SaaS Cold Call', description: 'Cold calling a Fortune 500 CTO about cloud migration', industry: 'Technology', difficulty: 'advanced', buyerPersona: 'CTO, risk-averse, data-driven', objectives: 'Book a demo meeting within 5 minutes' },
      { title: 'SMB Software Upsell', description: 'Upgrading existing customer from basic to premium plan', industry: 'Technology', difficulty: 'intermediate', buyerPersona: 'Small business owner, budget-conscious', objectives: 'Upgrade to premium tier' },
      { title: 'Healthcare Solution Pitch', description: 'Presenting EHR system to hospital board', industry: 'Healthcare', difficulty: 'advanced', buyerPersona: 'Hospital CEO, compliance-focused', objectives: 'Get board approval for pilot' },
      { title: 'Financial Services Cross-Sell', description: 'Cross-selling wealth management to existing banking client', industry: 'Finance', difficulty: 'intermediate', buyerPersona: 'High net worth individual', objectives: 'Open wealth management account' },
      { title: 'Manufacturing Equipment Renewal', description: 'Renewing a 3-year equipment maintenance contract', industry: 'Manufacturing', difficulty: 'beginner', buyerPersona: 'Operations Manager, efficiency-focused', objectives: 'Renew contract with 10% increase' },
      { title: 'Retail POS System Demo', description: 'Demonstrating new POS system to retail chain', industry: 'Retail', difficulty: 'beginner', buyerPersona: 'Retail VP Operations', objectives: 'Schedule pilot in 3 stores' },
      { title: 'Cybersecurity Incident Response', description: 'Selling incident response retainer after a breach scare', industry: 'Technology', difficulty: 'advanced', buyerPersona: 'CISO, recently experienced security incident', objectives: 'Sign annual retainer agreement' },
      { title: 'Real Estate CRM Migration', description: 'Convincing brokerage to switch from legacy CRM', industry: 'Real Estate', difficulty: 'intermediate', buyerPersona: 'Brokerage Owner, tech-hesitant', objectives: 'Commit to 6-month trial' },
      { title: 'EdTech Platform Expansion', description: 'Expanding LMS deployment across university system', industry: 'Education', difficulty: 'intermediate', buyerPersona: 'University Provost, ROI-focused', objectives: 'Expand to all departments' },
      { title: 'Insurance Bundle Negotiation', description: 'Negotiating multi-line insurance bundle for mid-market company', industry: 'Insurance', difficulty: 'advanced', buyerPersona: 'CFO, cost-optimization driven', objectives: 'Close bundle with 20% premium' },
      { title: 'Startup Seed Round Pitch', description: 'Pitching your SaaS product to a VC-backed startup', industry: 'Technology', difficulty: 'beginner', buyerPersona: 'Startup CEO, growth-focused', objectives: 'Convert to paid customer' },
      { title: 'Government Contract Bid', description: 'Presenting proposal for government IT modernization', industry: 'Government', difficulty: 'advanced', buyerPersona: 'Government Procurement Officer', objectives: 'Win the RFP evaluation' },
      { title: 'Pharmaceutical Sales Visit', description: 'Detailing new medication to physician practice', industry: 'Healthcare', difficulty: 'intermediate', buyerPersona: 'Lead Physician, evidence-based', objectives: 'Get formulary consideration' },
      { title: 'Logistics SaaS Platform', description: 'Selling supply chain visibility platform', industry: 'Logistics', difficulty: 'intermediate', buyerPersona: 'VP Supply Chain, operational efficiency', objectives: 'Start proof of concept' },
      { title: 'Media Ad Tech Solution', description: 'Presenting programmatic ad platform to agency', industry: 'Media', difficulty: 'beginner', buyerPersona: 'Media Director, ROI-focused', objectives: 'Run a $50K test campaign' }
    ]);

    // 2. Role Play Sessions (15)
    await RolePlaySession.bulkCreate([
      { title: 'Enterprise Discovery Call', scenarioId: 1, userId: 1, transcript: 'Rep: Good morning, this is John from TechSolutions...\nBuyer: I have 2 minutes...', score: 85, feedback: 'Strong opening, good objection handling', duration: 420, status: 'completed' },
      { title: 'SMB Upgrade Conversation', scenarioId: 2, userId: 2, transcript: 'Rep: Hi Sarah, I noticed your team has been growing...\nBuyer: We are but budget is tight...', score: 78, feedback: 'Good value prop but missed pricing anchor', duration: 360, status: 'completed' },
      { title: 'Hospital Board Presentation', scenarioId: 3, userId: 3, transcript: 'Rep: Thank you for the opportunity to present...\nBoard: What about HIPAA compliance?', score: 92, feedback: 'Excellent compliance knowledge, strong close', duration: 1800, status: 'reviewed' },
      { title: 'Wealth Management Intro', scenarioId: 4, userId: 4, transcript: 'Rep: Based on your portfolio growth...\nClient: I am happy with my current advisor...', score: 71, feedback: 'Need stronger differentiation from competitors', duration: 480, status: 'completed' },
      { title: 'Contract Renewal Discussion', scenarioId: 5, userId: 1, transcript: 'Rep: Your contract renewal is coming up...\nBuyer: We want to negotiate the price down...', score: 88, feedback: 'Handled price objection well, maintained value focus', duration: 300, status: 'reviewed' },
      { title: 'POS Demo Walk-through', scenarioId: 6, userId: 2, transcript: 'Rep: Let me show you our checkout speed...\nBuyer: Our current system works fine...', score: 82, feedback: 'Good demo flow, add more ROI metrics', duration: 900, status: 'completed' },
      { title: 'Security Pitch After Breach', scenarioId: 7, userId: 3, transcript: 'Rep: Given last month incident...\nCISO: We are evaluating multiple vendors...', score: 90, feedback: 'Perfect urgency creation without fear-mongering', duration: 600, status: 'reviewed' },
      { title: 'CRM Migration Pitch', scenarioId: 8, userId: 4, transcript: 'Rep: Your agents are spending 3 hours on data entry...\nOwner: Migration seems risky...', score: 75, feedback: 'Good pain identification, address migration risk better', duration: 540, status: 'completed' },
      { title: 'University LMS Expansion', scenarioId: 9, userId: 1, transcript: 'Rep: The pilot results show 40% improvement...\nProvost: What about faculty adoption?', score: 86, feedback: 'Strong data usage, add faculty testimonials', duration: 720, status: 'completed' },
      { title: 'Insurance Bundle Deal', scenarioId: 10, userId: 2, transcript: 'Rep: By bundling your coverage...\nCFO: Show me the total cost comparison...', score: 79, feedback: 'Need clearer cost-benefit analysis', duration: 660, status: 'completed' },
      { title: 'Startup Conversion Call', scenarioId: 11, userId: 3, transcript: 'Rep: Your trial ends next week...\nCEO: We love it but cash is tight...', score: 91, feedback: 'Excellent flexible pricing approach', duration: 240, status: 'reviewed' },
      { title: 'Government RFP Presentation', scenarioId: 12, userId: 4, transcript: 'Rep: Our FedRAMP certified platform...\nOfficer: What about Section 508 compliance?', score: 83, feedback: 'Strong compliance angle, improve timeline specifics', duration: 2400, status: 'completed' },
      { title: 'Pharma Detail Visit', scenarioId: 13, userId: 1, transcript: 'Rep: The Phase III trial showed...\nPhysician: What about the side effect profile?', score: 87, feedback: 'Strong clinical evidence presentation', duration: 480, status: 'completed' },
      { title: 'Logistics Platform Demo', scenarioId: 14, userId: 2, transcript: 'Rep: Real-time visibility across your entire chain...\nVP: Integration with our ERP?', score: 80, feedback: 'Good demo, need more integration details', duration: 600, status: 'completed' },
      { title: 'Ad Tech Pitch Meeting', scenarioId: 15, userId: 3, transcript: 'Rep: Our platform delivers 3x ROAS...\nDirector: We have tried similar tools before...', score: 76, feedback: 'Add more case studies and proof points', duration: 540, status: 'completed' }
    ]);

    // 3. Objections (15)
    await Objection.bulkCreate([
      { objectionText: 'Your price is too high compared to competitors', category: 'Price', suggestedResponse: 'I understand budget is important. Let me show you the total cost of ownership comparison including implementation, support, and ROI over 3 years...', industry: 'General', difficulty: 'medium', frequency: 'common' },
      { objectionText: 'We already have a solution in place', category: 'Status Quo', suggestedResponse: 'That makes sense - you have invested time and resources. Many of our best customers came from similar solutions. May I ask what prompted you to take this meeting?', industry: 'Technology', difficulty: 'medium', frequency: 'common' },
      { objectionText: 'I need to think about it', category: 'Stall', suggestedResponse: 'Absolutely, this is an important decision. To help your evaluation, what specific aspects would you like more clarity on?', industry: 'General', difficulty: 'easy', frequency: 'common' },
      { objectionText: 'We do not have the budget right now', category: 'Budget', suggestedResponse: 'I appreciate the transparency. When does your next budget cycle begin? In the meantime, let me show you our ROI calculator to help build the business case...', industry: 'General', difficulty: 'medium', frequency: 'common' },
      { objectionText: 'Send me some information and I will review it', category: 'Brush-off', suggestedResponse: 'Happy to send materials. To ensure I send the most relevant info, could you tell me which aspect is most important - the technical capabilities, ROI data, or implementation process?', industry: 'General', difficulty: 'easy', frequency: 'common' },
      { objectionText: 'We had a bad experience with a similar product', category: 'Past Experience', suggestedResponse: 'I am sorry to hear that. May I ask what went wrong? Understanding those pain points helps me show you specifically how our approach differs...', industry: 'Technology', difficulty: 'hard', frequency: 'occasional' },
      { objectionText: 'Your company is too small for our needs', category: 'Trust', suggestedResponse: 'That is a valid concern. Let me share some enterprise references including [Company X] with 50,000 users. Our dedicated enterprise team ensures white-glove service...', industry: 'Enterprise', difficulty: 'hard', frequency: 'occasional' },
      { objectionText: 'The implementation timeline is too long', category: 'Timeline', suggestedResponse: 'I understand speed to value matters. Our fast-track program can get core features live in 2 weeks. We can prioritize your must-haves and add features in phases...', industry: 'Technology', difficulty: 'medium', frequency: 'occasional' },
      { objectionText: 'I am not the decision maker', category: 'Authority', suggestedResponse: 'Thank you for letting me know. Would it be helpful if I prepared a brief executive summary you could share? Or would a joint call with the decision maker work better?', industry: 'General', difficulty: 'easy', frequency: 'common' },
      { objectionText: 'We are locked into a contract with your competitor', category: 'Contract', suggestedResponse: 'When does that contract expire? We can plan a seamless transition and I can show you how our buyout program works for qualified accounts...', industry: 'General', difficulty: 'hard', frequency: 'occasional' },
      { objectionText: 'I do not see how this is different from what we have', category: 'Differentiation', suggestedResponse: 'Great question. The three key differentiators are: [1] our AI-powered analytics, [2] real-time collaboration features, and [3] our industry-leading 99.99% uptime SLA...', industry: 'Technology', difficulty: 'medium', frequency: 'common' },
      { objectionText: 'We need to evaluate other options first', category: 'Competition', suggestedResponse: 'Thorough evaluation is smart. To save you time, here is our competitive comparison matrix. Would it help if I addressed any specific vendor you are evaluating?', industry: 'General', difficulty: 'medium', frequency: 'common' },
      { objectionText: 'This is not a priority right now', category: 'Timing', suggestedResponse: 'I understand. Many companies say that until they see the cost of delay. Would a quick 5-minute ROI analysis help determine if this should be prioritized?', industry: 'General', difficulty: 'medium', frequency: 'occasional' },
      { objectionText: 'Our team will not adopt a new tool', category: 'Adoption', suggestedResponse: 'Change management is crucial. Our platform includes built-in training, and we see 90% adoption in 30 days. I can share our adoption playbook and success stories...', industry: 'Technology', difficulty: 'hard', frequency: 'occasional' },
      { objectionText: 'What happens if your company goes out of business?', category: 'Risk', suggestedResponse: 'Smart question. We have $50M in funding, 500+ enterprise customers, and your data is always exportable. We also offer source code escrow for enterprise clients...', industry: 'Technology', difficulty: 'hard', frequency: 'rare' }
    ]);

    // 4. Pitch Practices (15)
    await PitchPractice.bulkCreate([
      { title: 'Cloud Migration Elevator Pitch', userId: 1, pitchText: 'In 60 seconds: Companies waste 40% of cloud spend due to poor optimization. Our AI platform automatically right-sizes resources, saving an average of $2M annually.', productName: 'CloudOptimize Pro', targetAudience: 'CTO/CIO', score: 88, status: 'reviewed' },
      { title: 'HR Tech Platform Pitch', userId: 2, pitchText: 'Imagine reducing employee turnover by 35%. Our predictive analytics identify flight risks 6 months before resignation, giving you time to intervene.', productName: 'RetainIQ', targetAudience: 'CHRO', score: 82, status: 'reviewed' },
      { title: 'Cybersecurity Suite Demo Pitch', userId: 3, pitchText: 'Last year, the average breach cost was $4.45M. Our unified security platform detects and responds to threats in under 60 seconds, 10x faster than industry average.', productName: 'SecureShield 360', targetAudience: 'CISO', score: 91, status: 'reviewed' },
      { title: 'Supply Chain Visibility', userId: 4, pitchText: 'Supply chain disruptions cost companies 45% of annual profits. Our real-time visibility platform predicts disruptions 2 weeks in advance with 94% accuracy.', productName: 'ChainSight', targetAudience: 'VP Supply Chain', score: 79, status: 'submitted' },
      { title: 'Sales Enablement Tool', userId: 1, pitchText: 'Your reps spend 65% of their time on non-selling activities. Our platform automates admin work, delivering 4 more selling hours per rep per week.', productName: 'SalesBoost AI', targetAudience: 'VP Sales', score: 85, status: 'reviewed' },
      { title: 'Customer Success Platform', userId: 2, pitchText: 'Reducing churn by just 5% increases profits by 95%. Our CS platform uses AI to identify at-risk accounts and recommend personalized retention strategies.', productName: 'ChurnGuard', targetAudience: 'VP Customer Success', score: 77, status: 'submitted' },
      { title: 'Marketing Attribution Pitch', userId: 3, pitchText: 'Most companies waste 30% of their marketing budget on underperforming channels. Our multi-touch attribution model shows exactly which touchpoints drive revenue.', productName: 'AttriBright', targetAudience: 'CMO', score: 83, status: 'reviewed' },
      { title: 'DevOps Automation Pitch', userId: 4, pitchText: 'Manual deployments cause 60% of production incidents. Our GitOps platform enables zero-downtime deployments with automatic rollback in under 30 seconds.', productName: 'DeployPilot', targetAudience: 'VP Engineering', score: 90, status: 'reviewed' },
      { title: 'Data Analytics Platform', userId: 1, pitchText: 'Your data team spends 80% of time on data prep. Our no-code analytics platform empowers business users to build dashboards in minutes, not weeks.', productName: 'DataFlow Pro', targetAudience: 'CDO', score: 86, status: 'reviewed' },
      { title: 'Employee Wellness Platform', userId: 2, pitchText: 'Burnout costs employers $300B annually. Our wellness platform uses AI coaching to improve wellbeing scores by 40% and reduce sick days by 25%.', productName: 'WellnessAI', targetAudience: 'CHRO', score: 74, status: 'submitted' },
      { title: 'Legal Tech Contract Review', userId: 3, pitchText: 'Manual contract review takes 90 minutes per document. Our AI reviews contracts in 3 minutes with 99% accuracy, flagging risks your team might miss.', productName: 'ContractIQ', targetAudience: 'General Counsel', score: 88, status: 'reviewed' },
      { title: 'Fintech Payment Solution', userId: 4, pitchText: 'Payment failures cause 10% revenue leakage. Our smart retry engine recovers 75% of failed payments, adding an average of $500K in annual recovered revenue.', productName: 'PayRecover', targetAudience: 'CFO', score: 81, status: 'submitted' },
      { title: 'IoT Fleet Management', userId: 1, pitchText: 'Fleet fuel costs up 30% this year. Our IoT platform optimizes routes in real-time, reducing fuel consumption by 20% and maintenance costs by 35%.', productName: 'FleetIQ', targetAudience: 'VP Operations', score: 84, status: 'reviewed' },
      { title: 'Compliance Automation', userId: 2, pitchText: 'Regulatory fines exceeded $10B last year. Our automated compliance platform continuously monitors your systems and generates audit-ready reports in one click.', productName: 'ComplianceBot', targetAudience: 'Chief Compliance Officer', score: 87, status: 'reviewed' },
      { title: 'AI Customer Service Bot', userId: 3, pitchText: 'Support tickets growing 40% YoY but your budget is flat. Our AI handles 70% of tier-1 tickets with 95% satisfaction, freeing agents for complex issues.', productName: 'SupportGenius', targetAudience: 'VP Support', score: 92, status: 'reviewed' }
    ]);

    // 5. Playbooks (15)
    await Playbook.bulkCreate([
      { title: 'Enterprise Discovery Playbook', description: 'Complete guide for running effective discovery calls with enterprise prospects', category: 'Discovery', steps: '1. Research the company\n2. Prepare 5 open-ended questions\n3. Map stakeholders\n4. Identify 3 pain points\n5. Qualify budget and timeline', bestPractices: 'Always lead with questions, not features. Listen 70%, talk 30%.', industry: 'Enterprise', status: 'active' },
      { title: 'MEDDPICC Qualification', description: 'Using MEDDPICC framework for deal qualification', category: 'Qualification', steps: '1. Metrics - Quantify the value\n2. Economic Buyer - Identify\n3. Decision Criteria - Understand\n4. Decision Process - Map\n5. Paper Process - Navigate\n6. Identify Pain - Prioritize\n7. Champion - Develop\n8. Competition - Assess', bestPractices: 'Update MEDDPICC score after every call. Share with team weekly.', industry: 'Technology', status: 'active' },
      { title: 'Inbound Lead Follow-up', description: 'Best practices for handling inbound marketing qualified leads', category: 'Inbound', steps: '1. Respond within 5 minutes\n2. Reference their specific action\n3. Ask qualifying questions\n4. Offer immediate value\n5. Book next step', bestPractices: 'Speed to lead is critical. First response under 5 minutes wins 50% more deals.', industry: 'General', status: 'active' },
      { title: 'Competitive Displacement', description: 'How to win deals against established competitors', category: 'Competitive', steps: '1. Understand current solution\n2. Identify dissatisfaction triggers\n3. Calculate switching cost vs value\n4. Provide migration plan\n5. Offer pilot program', bestPractices: 'Never bash competitors. Focus on your unique strengths and the cost of status quo.', industry: 'Technology', status: 'active' },
      { title: 'Executive Presentation', description: 'Framework for C-suite pitch meetings', category: 'Presentation', steps: '1. Open with industry insight\n2. Present 3 key business outcomes\n3. Show relevant case study\n4. Address risk mitigation\n5. Propose clear next steps', bestPractices: 'Executives want business outcomes, not features. Keep to 15 minutes max.', industry: 'Enterprise', status: 'active' },
      { title: 'Multi-Threading Strategy', description: 'Building relationships across the buying committee', category: 'Stakeholders', steps: '1. Map org chart\n2. Identify champions and blockers\n3. Create personalized value props\n4. Schedule individual touchpoints\n5. Orchestrate group meeting', bestPractices: 'Never rely on a single thread. 3+ contacts in a deal increases win rate by 40%.', industry: 'Enterprise', status: 'active' },
      { title: 'Pricing Negotiation', description: 'Handling pricing discussions and discount requests', category: 'Negotiation', steps: '1. Anchor high with full value\n2. Understand budget constraints\n3. Trade value for concessions\n4. Use packaging to protect price\n5. Create urgency with time-limited offer', bestPractices: 'Never lead with discounts. Always trade something for any price reduction.', industry: 'General', status: 'active' },
      { title: 'Account Expansion', description: 'Growing revenue within existing accounts', category: 'Expansion', steps: '1. Review usage analytics\n2. Identify expansion triggers\n3. Map new stakeholders\n4. Present success metrics\n5. Propose expansion plan', bestPractices: 'It costs 5x more to acquire than expand. Prioritize your install base.', industry: 'SaaS', status: 'active' },
      { title: 'Channel Partner Sales', description: 'Working effectively with channel partners', category: 'Partners', steps: '1. Align on target accounts\n2. Share battle cards\n3. Joint account planning\n4. Coordinate outreach\n5. Track partner-sourced pipeline', bestPractices: 'Invest in partner enablement. Trained partners close 30% faster.', industry: 'Technology', status: 'active' },
      { title: 'Cold Outbound Sequence', description: 'Multi-touch outbound prospecting cadence', category: 'Prospecting', steps: '1. Day 1: Personalized email\n2. Day 3: LinkedIn connection\n3. Day 5: Phone call\n4. Day 7: Value-add email\n5. Day 10: Break-up email', bestPractices: '8-12 touches over 3 weeks. Mix channels. Personalize every message.', industry: 'General', status: 'active' },
      { title: 'Demo Best Practices', description: 'Running effective product demonstrations', category: 'Demo', steps: '1. Recap discovery findings\n2. Show 3 relevant use cases\n3. Let prospect drive\n4. Address questions in real-time\n5. Summarize value and next steps', bestPractices: 'Never do a feature dump. Tell, show, tell. Customize to their use case.', industry: 'Technology', status: 'active' },
      { title: 'Renewal Management', description: 'Ensuring high renewal rates', category: 'Retention', steps: '1. Start 90 days before renewal\n2. Review health score\n3. Conduct business review\n4. Present ROI report\n5. Negotiate renewal terms', bestPractices: 'Renewals are won in the first 90 days of the contract, not the last 90.', industry: 'SaaS', status: 'active' },
      { title: 'Social Selling Playbook', description: 'Leveraging LinkedIn for sales', category: 'Social', steps: '1. Optimize your profile\n2. Share thought leadership weekly\n3. Engage with prospect content\n4. Send personalized InMails\n5. Convert to offline conversation', bestPractices: 'Social sellers create 45% more opportunities. Be consistent and authentic.', industry: 'General', status: 'active' },
      { title: 'Proof of Concept Framework', description: 'Running successful POCs and trials', category: 'POC', steps: '1. Define success criteria upfront\n2. Assign dedicated resources\n3. Weekly check-ins\n4. Document results\n5. Present findings to decision makers', bestPractices: 'Agree on success criteria before starting. Time-box to 30 days max.', industry: 'Technology', status: 'active' },
      { title: 'Mutual Action Plan', description: 'Creating joint close plans with prospects', category: 'Closing', steps: '1. Align on desired outcome\n2. Map all steps to close\n3. Assign owners and dates\n4. Review weekly\n5. Adjust timeline as needed', bestPractices: 'Shared plans increase close rates by 30%. Get buyer commitment on dates.', industry: 'Enterprise', status: 'active' }
    ]);

    // 6. Performance Metrics (15)
    await PerformanceMetric.bulkCreate([
      { userId: 1, metricName: 'Calls Made', metricValue: 156, category: 'Activity', period: 'March 2024', trend: 'up', notes: 'Increased by 20% from last month' },
      { userId: 1, metricName: 'Meetings Booked', metricValue: 32, category: 'Activity', period: 'March 2024', trend: 'up', notes: 'Best month this quarter' },
      { userId: 2, metricName: 'Pipeline Generated', metricValue: 450000, category: 'Revenue', period: 'March 2024', trend: 'up', notes: '$450K in new pipeline' },
      { userId: 2, metricName: 'Win Rate', metricValue: 34.5, category: 'Efficiency', period: 'Q1 2024', trend: 'stable', notes: 'Consistent with last quarter' },
      { userId: 3, metricName: 'Average Deal Size', metricValue: 85000, category: 'Revenue', period: 'Q1 2024', trend: 'up', notes: 'Up from $72K last quarter' },
      { userId: 3, metricName: 'Sales Cycle Length', metricValue: 45, category: 'Efficiency', period: 'Q1 2024', trend: 'down', notes: 'Reduced from 52 days' },
      { userId: 4, metricName: 'Quota Attainment', metricValue: 112, category: 'Revenue', period: 'March 2024', trend: 'up', notes: '112% of monthly quota' },
      { userId: 4, metricName: 'Demo Conversion Rate', metricValue: 42, category: 'Efficiency', period: 'March 2024', trend: 'up', notes: 'Above team average of 35%' },
      { userId: 1, metricName: 'Email Response Rate', metricValue: 28, category: 'Activity', period: 'March 2024', trend: 'stable', notes: '28% response rate on cold outreach' },
      { userId: 2, metricName: 'Customer Satisfaction', metricValue: 4.8, category: 'Quality', period: 'Q1 2024', trend: 'up', notes: 'Out of 5.0 scale' },
      { userId: 3, metricName: 'Proposals Sent', metricValue: 24, category: 'Activity', period: 'March 2024', trend: 'up', notes: 'Increased from 18 last month' },
      { userId: 4, metricName: 'Revenue Closed', metricValue: 280000, category: 'Revenue', period: 'March 2024', trend: 'up', notes: '$280K closed this month' },
      { userId: 1, metricName: 'Objections Handled', metricValue: 89, category: 'Quality', period: 'March 2024', trend: 'up', notes: '89% successful objection handling' },
      { userId: 2, metricName: 'Follow-up Rate', metricValue: 95, category: 'Activity', period: 'March 2024', trend: 'stable', notes: '95% follow-up within 24 hours' },
      { userId: 3, metricName: 'Training Score', metricValue: 94, category: 'Quality', period: 'March 2024', trend: 'up', notes: 'Scored 94/100 on certification' }
    ]);

    // 7. Product Knowledge (15)
    await ProductKnowledge.bulkCreate([
      { productName: 'CloudOptimize Pro', description: 'AI-powered cloud cost optimization platform', features: 'Auto-scaling, Resource right-sizing, Cost anomaly detection, Reserved instance management', pricing: '$2,000/mo base + usage', competitiveAdvantage: 'Only platform with real-time ML-based optimization', targetMarket: 'Mid-market to Enterprise', category: 'Cloud' },
      { productName: 'SecureShield 360', description: 'Unified cybersecurity platform with XDR capabilities', features: 'Threat detection, Incident response, Vulnerability management, Compliance reporting', pricing: '$15/endpoint/mo', competitiveAdvantage: '60-second mean time to detect, 10x industry average', targetMarket: 'Enterprise', category: 'Security' },
      { productName: 'SalesBoost AI', description: 'AI-powered sales enablement and productivity platform', features: 'Auto-dialer, Email sequencing, AI coaching, Pipeline analytics', pricing: '$89/user/mo', competitiveAdvantage: 'Built-in AI coach that provides real-time call guidance', targetMarket: 'Sales Teams 10-500', category: 'Sales' },
      { productName: 'DataFlow Pro', description: 'No-code data analytics and visualization platform', features: 'Drag-drop dashboards, Auto-insights, Data connectors, Scheduled reports', pricing: '$50/user/mo', competitiveAdvantage: '300+ native connectors, setup in hours not weeks', targetMarket: 'Business Analysts', category: 'Analytics' },
      { productName: 'RetainIQ', description: 'Predictive employee retention platform', features: 'Flight risk scoring, Engagement surveys, Action recommendations, Benchmarking', pricing: '$5/employee/mo', competitiveAdvantage: 'Predicts turnover 6 months in advance with 85% accuracy', targetMarket: 'HR Teams 100+ employees', category: 'HR Tech' },
      { productName: 'ChainSight', description: 'Real-time supply chain visibility platform', features: 'Live tracking, Disruption prediction, Supplier scorecards, Inventory optimization', pricing: '$3,000/mo', competitiveAdvantage: 'Predicts disruptions 2 weeks in advance with 94% accuracy', targetMarket: 'Manufacturing & Logistics', category: 'Supply Chain' },
      { productName: 'ComplianceBot', description: 'Automated regulatory compliance monitoring', features: 'Continuous monitoring, Auto-remediation, Audit reports, Policy management', pricing: '$1,500/mo', competitiveAdvantage: 'Covers SOC2, HIPAA, GDPR, PCI in one platform', targetMarket: 'Regulated Industries', category: 'Compliance' },
      { productName: 'SupportGenius', description: 'AI-powered customer support automation', features: 'AI chatbot, Ticket routing, Sentiment analysis, Knowledge base', pricing: '$30/agent/mo', competitiveAdvantage: 'Resolves 70% of tier-1 tickets automatically', targetMarket: 'Support Teams', category: 'Support' },
      { productName: 'ContractIQ', description: 'AI contract review and management platform', features: 'AI review, Risk flagging, Template library, E-signature, Analytics', pricing: '$200/user/mo', competitiveAdvantage: 'Reviews contracts in 3 minutes vs 90 minutes manually', targetMarket: 'Legal Teams', category: 'Legal Tech' },
      { productName: 'PayRecover', description: 'Smart payment recovery and retry engine', features: 'Smart retry logic, Dunning management, Payment analytics, Revenue recovery', pricing: '1% of recovered revenue', competitiveAdvantage: 'Recovers 75% of failed payments vs 30% industry avg', targetMarket: 'SaaS Companies', category: 'Fintech' },
      { productName: 'FleetIQ', description: 'IoT-powered fleet management platform', features: 'Route optimization, Predictive maintenance, Fuel management, Driver safety', pricing: '$25/vehicle/mo', competitiveAdvantage: 'Reduces fuel costs 20% and maintenance costs 35%', targetMarket: 'Fleet Operators 50+', category: 'IoT' },
      { productName: 'WellnessAI', description: 'Employee wellness and mental health platform', features: 'AI coaching, Stress tracking, Team insights, Resource library', pricing: '$8/employee/mo', competitiveAdvantage: 'AI coach available 24/7 with clinical-grade assessments', targetMarket: 'Companies 200+ employees', category: 'Wellness' },
      { productName: 'AttriBright', description: 'Multi-touch marketing attribution platform', features: 'Cross-channel tracking, ROI modeling, Budget optimization, A/B testing', pricing: '$1,000/mo', competitiveAdvantage: 'Only platform combining attribution with budget optimization AI', targetMarket: 'Marketing Teams', category: 'Marketing' },
      { productName: 'DeployPilot', description: 'GitOps deployment automation platform', features: 'Zero-downtime deploys, Auto-rollback, Canary releases, Compliance gates', pricing: '$100/developer/mo', competitiveAdvantage: 'Auto-rollback in under 30 seconds on any anomaly', targetMarket: 'Engineering Teams', category: 'DevOps' },
      { productName: 'ChurnGuard', description: 'AI customer success and churn prevention', features: 'Health scoring, Playbook automation, Expansion signals, QBR builder', pricing: '$45/user/mo', competitiveAdvantage: 'Identifies at-risk accounts 60 days before churn', targetMarket: 'CS Teams', category: 'Customer Success' }
    ]);

    // 8. Coaching Plans (15)
    await CoachingPlan.bulkCreate([
      { title: 'New Rep Onboarding - John', userId: 1, goals: 'Master product demo, complete certification, close first deal', milestones: 'Week 1: Shadow calls\nWeek 2: Product cert\nWeek 3: First solo call\nWeek 4: First close', currentPhase: 'Week 3', startDate: '2024-03-01', endDate: '2024-04-01', status: 'active' },
      { title: 'Objection Handling Mastery', userId: 2, goals: 'Handle 90%+ objections successfully, reduce talk-to-listen ratio', milestones: 'Month 1: Study common objections\nMonth 2: Role-play practice\nMonth 3: Live call coaching', currentPhase: 'Month 2', startDate: '2024-02-15', endDate: '2024-05-15', status: 'active' },
      { title: 'Enterprise Selling Skills', userId: 3, goals: 'Close first $100K+ deal, master multi-threading', milestones: 'Phase 1: MEDDPICC training\nPhase 2: Executive presence\nPhase 3: Complex deal management', currentPhase: 'Phase 2', startDate: '2024-01-15', endDate: '2024-06-15', status: 'active' },
      { title: 'Discovery Call Excellence', userId: 4, goals: 'Improve discovery call conversion by 25%', milestones: 'Week 1-2: Question framework\nWeek 3-4: Active listening\nWeek 5-6: Pain amplification', currentPhase: 'Week 3-4', startDate: '2024-03-01', endDate: '2024-04-15', status: 'active' },
      { title: 'Closing Techniques Workshop', userId: 1, goals: 'Learn and apply 5 closing techniques, improve close rate by 15%', milestones: 'Session 1: Trial close\nSession 2: Assumptive close\nSession 3: Summary close\nSession 4: Urgency close\nSession 5: Alternative close', currentPhase: 'Session 3', startDate: '2024-02-01', endDate: '2024-04-01', status: 'active' },
      { title: 'Presentation Skills Development', userId: 2, goals: 'Deliver compelling executive presentations', milestones: 'Module 1: Storytelling\nModule 2: Visual design\nModule 3: Delivery practice\nModule 4: Q&A handling', currentPhase: 'Module 2', startDate: '2024-03-10', endDate: '2024-05-10', status: 'active' },
      { title: 'Pipeline Management Mastery', userId: 3, goals: 'Maintain 3x pipeline coverage, improve forecast accuracy to 90%', milestones: 'Step 1: Pipeline hygiene audit\nStep 2: Stage criteria mastery\nStep 3: Weekly forecasting practice', currentPhase: 'Step 2', startDate: '2024-01-01', endDate: '2024-03-31', status: 'active' },
      { title: 'Negotiation Skills Program', userId: 4, goals: 'Reduce discounting by 20%, maintain deal velocity', milestones: 'Week 1: BATNA framework\nWeek 2: Value-based pricing\nWeek 3: Concession trading\nWeek 4: Contract terms', currentPhase: 'Week 2', startDate: '2024-03-05', endDate: '2024-04-05', status: 'active' },
      { title: 'Social Selling Bootcamp', userId: 1, goals: 'Generate 5 qualified leads per month from LinkedIn', milestones: 'Week 1: Profile optimization\nWeek 2: Content strategy\nWeek 3: Engagement plan\nWeek 4: Conversion tactics', currentPhase: 'Week 1', startDate: '2024-03-15', endDate: '2024-04-15', status: 'active' },
      { title: 'Technical Product Expertise', userId: 2, goals: 'Pass advanced technical certification, handle technical objections', milestones: 'Module 1: Architecture deep dive\nModule 2: Integration patterns\nModule 3: Security & compliance\nModule 4: Certification exam', currentPhase: 'Module 1', startDate: '2024-03-20', endDate: '2024-06-20', status: 'active' },
      { title: 'Account Planning Workshop', userId: 3, goals: 'Create strategic account plans for top 10 accounts', milestones: 'Step 1: Account research\nStep 2: Stakeholder mapping\nStep 3: Opportunity identification\nStep 4: Action plan creation', currentPhase: 'Step 1', startDate: '2024-03-01', endDate: '2024-04-30', status: 'active' },
      { title: 'Email Copywriting Mastery', userId: 4, goals: 'Increase email response rate from 15% to 30%', milestones: 'Lesson 1: Subject lines\nLesson 2: Personalization\nLesson 3: Call-to-action\nLesson 4: Follow-up sequences', currentPhase: 'Lesson 2', startDate: '2024-03-10', endDate: '2024-04-10', status: 'active' },
      { title: 'Time Management for Sales', userId: 1, goals: 'Increase selling time from 35% to 60% of work day', milestones: 'Week 1: Time audit\nWeek 2: Priority matrix\nWeek 3: Automation setup\nWeek 4: New routine', currentPhase: 'Week 2', startDate: '2024-03-01', endDate: '2024-03-31', status: 'active' },
      { title: 'Cross-Functional Collaboration', userId: 2, goals: 'Improve SE and CSM collaboration, reduce handoff friction', milestones: 'Phase 1: Process mapping\nPhase 2: Handoff templates\nPhase 3: Joint planning sessions', currentPhase: 'Phase 1', startDate: '2024-03-15', endDate: '2024-05-15', status: 'active' },
      { title: 'Quarterly Business Review', userId: 3, goals: 'Master QBR delivery, drive 100% renewal rate', milestones: 'Step 1: QBR template creation\nStep 2: Data collection\nStep 3: Practice delivery\nStep 4: Feedback incorporation', currentPhase: 'Step 2', startDate: '2024-02-01', endDate: '2024-03-31', status: 'completed' }
    ]);

    // 9. Call Scripts (15)
    await CallScript.bulkCreate([
      { title: 'Cold Call Opening - Decision Maker', scriptType: 'Cold Call', content: 'Hi [Name], this is [Your Name] from [Company]. I know I am catching you out of the blue. I noticed [Company] recently [trigger event]. We have helped similar companies [benefit]. Do you have 30 seconds to hear how?', industry: 'Technology', talkingPoints: 'Trigger event reference, Social proof, Quick value prop', closingTechnique: 'Time-bound ask', status: 'active' },
      { title: 'Gatekeeper Navigation', scriptType: 'Cold Call', content: 'Good morning, this is [Your Name]. I am hoping you can help me. I need to reach [Decision Maker Name] regarding [business topic]. Would you be able to connect me?', industry: 'General', talkingPoints: 'Be polite, Use the DM name, State business purpose', closingTechnique: 'Help me approach', status: 'active' },
      { title: 'Voicemail Script - First Touch', scriptType: 'Voicemail', content: 'Hi [Name], this is [Your Name] from [Company]. I am calling because [specific reason]. Companies like [reference customer] have seen [specific result]. I would love 10 minutes to explore if we can help [Company] achieve similar results. My number is [number]. Again, that is [Your Name] from [Company].', industry: 'General', talkingPoints: 'Specific reason, Reference customer, Clear CTA', closingTechnique: 'Callback request', status: 'active' },
      { title: 'Discovery Call Framework', scriptType: 'Discovery', content: 'Thanks for taking the time today, [Name]. Before we dive in, I have done some research on [Company] and I am curious about a few things. Can you walk me through how your team currently handles [process]? What is working well? What would you change if you could?', industry: 'Technology', talkingPoints: 'Show research, Open-ended questions, Current state exploration', closingTechnique: 'Next step commitment', status: 'active' },
      { title: 'Demo Opening Script', scriptType: 'Demo', content: 'Great to have everyone here. Before I show you anything, let me recap what I heard from [Name] in our last conversation: [pain points]. Today I want to show you exactly how we address each of these. If at any point you see something relevant, please jump in.', industry: 'Technology', talkingPoints: 'Recap pain points, Set expectations, Invite interaction', closingTechnique: 'Interactive engagement', status: 'active' },
      { title: 'Follow-up After No Response', scriptType: 'Follow-up', content: 'Hi [Name], I reached out last week about [topic]. I know things get busy. I wanted to share a quick case study showing how [similar company] achieved [result]. Would a brief 15-minute call be worth your time this week?', industry: 'General', talkingPoints: 'Reference previous outreach, Provide value, Low commitment ask', closingTechnique: 'Low commitment close', status: 'active' },
      { title: 'Referral Request Script', scriptType: 'Referral', content: '[Name], I am glad we have been able to deliver [results] for your team. I am looking to help other companies with similar challenges. Is there anyone in your network who might benefit from a conversation? I promise to treat them with the same care we have shown you.', industry: 'General', talkingPoints: 'Acknowledge success, Specific ask, Promise of care', closingTechnique: 'Specific name request', status: 'active' },
      { title: 'Pricing Discussion Script', scriptType: 'Negotiation', content: 'Based on everything we have discussed, the solution that fits your needs is our [tier] package at [price]. This includes [key features]. Compared to the [cost of problem], this represents a [X]x return on investment within [timeframe]. How does this align with your budget expectations?', industry: 'General', talkingPoints: 'Value recap, ROI framing, Budget alignment', closingTechnique: 'Budget alignment close', status: 'active' },
      { title: 'Renewal Call Script', scriptType: 'Renewal', content: 'Hi [Name], your renewal is coming up in [timeframe]. Before we discuss terms, I want to share some highlights from this past year: [key metrics]. Your team has seen [specific results]. For next year, I recommend [package] to help you [next goal].', industry: 'SaaS', talkingPoints: 'Value delivered, Key metrics, Forward-looking recommendation', closingTechnique: 'Value-based renewal', status: 'active' },
      { title: 'Upsell Conversation', scriptType: 'Expansion', content: 'Hi [Name], I have been reviewing your account and noticed [usage pattern]. Based on what your team is doing, our [premium feature] could help you [specific benefit]. Several companies your size have added this and seen [result]. Would you be open to a quick demo?', industry: 'SaaS', talkingPoints: 'Usage data, Specific benefit, Social proof', closingTechnique: 'Demo offer close', status: 'active' },
      { title: 'Objection Response - Too Expensive', scriptType: 'Objection', content: 'I hear you, and price is an important factor. Let me ask - when you say too expensive, are you comparing to a specific alternative, or is it more about the total budget available? [Listen] Let me show you our TCO analysis which includes implementation, training, and the cost of not solving this problem...', industry: 'General', talkingPoints: 'Acknowledge concern, Clarify the objection, TCO framing', closingTechnique: 'Value reframe', status: 'active' },
      { title: 'Meeting Confirmation Call', scriptType: 'Pre-meeting', content: 'Hi [Name], I am looking forward to our meeting [day/time]. I want to make sure we use our time well. Is there anything specific you would like me to address? Also, would it be helpful to include anyone else from your team?', industry: 'General', talkingPoints: 'Confirm logistics, Set agenda, Expand attendees', closingTechnique: 'Confirmation close', status: 'active' },
      { title: 'Win-back Script', scriptType: 'Win-back', content: 'Hi [Name], it has been [time] since we last spoke. Since then, we have made significant improvements including [new features]. I understand [competitor] was a better fit at the time - would you be open to seeing what has changed?', industry: 'Technology', talkingPoints: 'Acknowledge time gap, Highlight improvements, Low-pressure ask', closingTechnique: 'Curiosity close', status: 'active' },
      { title: 'Partnership Proposal Call', scriptType: 'Partnership', content: 'Hi [Name], I have been following [Company]s work in [area]. I see a strong alignment between our solutions. Our customers often need [their capability] and their customers need [our capability]. Could we explore a partnership that benefits both our customer bases?', industry: 'Technology', talkingPoints: 'Research their company, Mutual benefit, Customer-centric framing', closingTechnique: 'Mutual benefit close', status: 'active' },
      { title: 'End-of-Quarter Push', scriptType: 'Closing', content: 'Hi [Name], I know we have been discussing this for [timeframe]. I want to be transparent - we have special terms available through [date] that include [incentive]. More importantly, every week you delay costs you [cost of delay]. Can we finalize this week?', industry: 'General', talkingPoints: 'Urgency creation, Special terms, Cost of delay', closingTechnique: 'Urgency close', status: 'active' }
    ]);

    // 10. Email Templates (15)
    await EmailTemplate.bulkCreate([
      { title: 'Cold Outreach - First Touch', subject: 'Quick question about [Company] growth plans', body: 'Hi [Name],\n\nI noticed [Company] is [trigger event]. When this happens, teams like yours often struggle with [pain point].\n\nWe helped [reference customer] solve this and they saw [specific result] in [timeframe].\n\nWorth a 15-minute conversation?\n\nBest,\n[Your Name]', templateType: 'Cold Outreach', industry: 'Technology', conversionRate: 12.5, status: 'active' },
      { title: 'Follow-up After Meeting', subject: 'Great connecting today - next steps', body: 'Hi [Name],\n\nThanks for the time today. Here is a recap:\n\n- Challenge: [their pain point]\n- Solution: [how we help]\n- Next Step: [agreed action]\n\nI am attaching the case study we discussed. Let me know if you have any questions before our next call on [date].\n\nBest,\n[Your Name]', templateType: 'Follow-up', industry: 'General', conversionRate: 45.0, status: 'active' },
      { title: 'Break-up Email', subject: 'Should I close your file?', body: 'Hi [Name],\n\nI have reached out a few times and haven not heard back. I understand timing may not be right.\n\nI will assume this is not a priority right now and close out your file. If things change, feel free to reach out anytime.\n\nWishing you the best,\n[Your Name]', templateType: 'Break-up', industry: 'General', conversionRate: 18.0, status: 'active' },
      { title: 'Case Study Share', subject: 'How [Company] achieved [result]', body: 'Hi [Name],\n\nI thought you would find this interesting - [Similar Company] was facing [same challenge as prospect].\n\nUsing our platform, they achieved:\n- [Result 1]\n- [Result 2]\n- [Result 3]\n\nI would love to explore if we can deliver similar results for [Company]. Open to a quick chat?\n\nBest,\n[Your Name]', templateType: 'Nurture', industry: 'Technology', conversionRate: 22.0, status: 'active' },
      { title: 'Post-Demo Follow-up', subject: 'Your personalized ROI analysis', body: 'Hi [Name],\n\nGreat demo today! Based on what you shared, here is your estimated impact:\n\n- Annual Savings: $[amount]\n- Productivity Gain: [X] hours/week\n- ROI Timeline: [X] months\n\nI have attached a detailed ROI report. Would [date] work to review this with [decision maker]?\n\nBest,\n[Your Name]', templateType: 'Post-Demo', industry: 'Technology', conversionRate: 38.0, status: 'active' },
      { title: 'Referral Request', subject: 'Quick favor to ask', body: 'Hi [Name],\n\nHope all is well! I love hearing about the results your team has been getting with [product].\n\nI am looking to help other [industry] companies achieve similar success. Would you happen to know anyone who might benefit from a conversation?\n\nHappy to make it easy - just reply with a name and I will take it from there.\n\nThanks!\n[Your Name]', templateType: 'Referral', industry: 'General', conversionRate: 25.0, status: 'active' },
      { title: 'Event Invitation', subject: 'You are invited: [Event Name]', body: 'Hi [Name],\n\nWe are hosting an exclusive [event type] on [date] featuring [speakers/topics].\n\nKey takeaways:\n- [Takeaway 1]\n- [Takeaway 2]\n- [Takeaway 3]\n\nSpots are limited to [number] attendees. Would you like me to reserve your seat?\n\nBest,\n[Your Name]', templateType: 'Event', industry: 'General', conversionRate: 15.0, status: 'active' },
      { title: 'Proposal Follow-up', subject: 'Thoughts on the proposal?', body: 'Hi [Name],\n\nI wanted to follow up on the proposal I sent [date]. I know these decisions take time, so I wanted to check if:\n\n1. You had a chance to review it\n2. Any questions I can address\n3. Anyone else needs to be involved\n\nI am available [times] if a quick call would help move things forward.\n\nBest,\n[Your Name]', templateType: 'Follow-up', industry: 'General', conversionRate: 32.0, status: 'active' },
      { title: 'Competitive Switch Offer', subject: 'Thinking of switching from [Competitor]?', body: 'Hi [Name],\n\nI have heard from several [Competitor] customers that [common complaint].\n\nOur customers who made the switch report:\n- [Benefit 1]\n- [Benefit 2]\n- [Migration in just X days]\n\nWe also offer a migration assistance program. Interested in learning more?\n\nBest,\n[Your Name]', templateType: 'Competitive', industry: 'Technology', conversionRate: 14.0, status: 'active' },
      { title: 'Renewal Reminder', subject: 'Your renewal is coming up - important updates', body: 'Hi [Name],\n\nYour [product] subscription renews on [date]. Before we process, I wanted to share:\n\n- Your team has [usage stats]\n- New features available: [features]\n- Your dedicated success manager: [name]\n\nLet us schedule a quick call to ensure you are set up for an even better year ahead.\n\nBest,\n[Your Name]', templateType: 'Renewal', industry: 'SaaS', conversionRate: 72.0, status: 'active' },
      { title: 'Trigger Event Outreach', subject: 'Congrats on [trigger event]!', body: 'Hi [Name],\n\nCongratulations on [trigger event - funding/hire/expansion]! \n\nWhen companies hit this milestone, they typically face [challenge]. We recently helped [similar company] navigate this and they [result].\n\nWould it be useful to share what we have learned?\n\nBest,\n[Your Name]', templateType: 'Trigger', industry: 'Technology', conversionRate: 20.0, status: 'active' },
      { title: 'Multi-stakeholder Introduction', subject: '[Mutual Contact] suggested we connect', body: 'Hi [Name],\n\n[Mutual Contact] mentioned you are leading [initiative] at [Company]. We have been working with [their team] on [related project] and they suggested our [solution] might help your team as well.\n\nWould you be open to a brief introduction call?\n\nBest,\n[Your Name]', templateType: 'Warm Intro', industry: 'Enterprise', conversionRate: 35.0, status: 'active' },
      { title: 'Executive Summary Email', subject: 'Executive Summary: [Company] x [Your Company]', body: 'Hi [Name],\n\nPer your request, here is a one-page summary for your leadership team:\n\nChallenge: [problem statement]\nSolution: [our approach]\nInvestment: [pricing]\nExpected ROI: [timeline and amount]\nNext Steps: [clear actions]\n\nI am available to join any internal discussions if helpful.\n\nBest,\n[Your Name]', templateType: 'Executive', industry: 'Enterprise', conversionRate: 42.0, status: 'active' },
      { title: 'Content Share - Thought Leadership', subject: 'New research: [Topic] trends for 2024', body: 'Hi [Name],\n\nOur team just published research on [topic] that I thought you would find valuable:\n\nKey findings:\n- [Finding 1]\n- [Finding 2]\n- [Finding 3]\n\nFull report here: [link]\n\nWould love to hear your thoughts. Are you seeing similar trends at [Company]?\n\nBest,\n[Your Name]', templateType: 'Content', industry: 'General', conversionRate: 10.0, status: 'active' },
      { title: 'Thank You After Close', subject: 'Welcome to the [Company] family!', body: 'Hi [Name],\n\nOn behalf of the entire team, welcome aboard! We are thrilled to partner with [Company].\n\nHere is what happens next:\n1. [Onboarding step 1]\n2. [Onboarding step 2]\n3. [Onboarding step 3]\n\nYour dedicated success manager [Name] will reach out within 24 hours.\n\nThank you for your trust in us.\n\nBest,\n[Your Name]', templateType: 'Post-Close', industry: 'General', conversionRate: 95.0, status: 'active' }
    ]);

    // 11. Deal Simulations (15)
    await DealSimulation.bulkCreate([
      { title: 'TechCorp Cloud Migration', dealValue: 250000, companyName: 'TechCorp Inc', industry: 'Technology', stage: 'Negotiation', stakeholders: 'CTO (Champion), CFO (Economic Buyer), VP Eng (Influencer)', challenges: 'Competing with AWS native tools, 6-month budget freeze', outcome: 'in_progress' },
      { title: 'HealthFirst EHR Upgrade', dealValue: 500000, companyName: 'HealthFirst Medical', industry: 'Healthcare', stage: 'Proposal', stakeholders: 'CMO (Champion), CEO (Decision Maker), IT Director (Technical)', challenges: 'HIPAA compliance concerns, staff training resistance', outcome: 'in_progress' },
      { title: 'RetailMax POS Rollout', dealValue: 180000, companyName: 'RetailMax Stores', industry: 'Retail', stage: 'Closed Won', stakeholders: 'VP Ops (Champion), CEO (Approver), Store Managers (Users)', challenges: 'Multi-location deployment, holiday timing', outcome: 'won' },
      { title: 'FinanceHub Platform Deal', dealValue: 750000, companyName: 'FinanceHub Capital', industry: 'Finance', stage: 'Discovery', stakeholders: 'CTO (Sponsor), CISO (Gatekeeper), Head of Trading (User)', challenges: 'Regulatory requirements, latency requirements', outcome: 'in_progress' },
      { title: 'EduTech University Contract', dealValue: 320000, companyName: 'State University System', industry: 'Education', stage: 'Evaluation', stakeholders: 'Provost (Champion), IT VP (Technical), Procurement (Process)', challenges: 'Government procurement process, accessibility requirements', outcome: 'in_progress' },
      { title: 'ManufacturePro Automation', dealValue: 420000, companyName: 'ManufacturePro Inc', industry: 'Manufacturing', stage: 'Closed Won', stakeholders: 'COO (Champion), Plant Managers (Users), CFO (Budget)', challenges: 'Legacy system integration, union concerns', outcome: 'won' },
      { title: 'SecureBank Cyber Deal', dealValue: 890000, companyName: 'SecureBank Financial', industry: 'Finance', stage: 'Negotiation', stakeholders: 'CISO (Champion), CTO (Technical), Board (Final Approval)', challenges: 'Board approval process, incumbent vendor relationship', outcome: 'in_progress' },
      { title: 'LogiFlow Supply Chain', dealValue: 275000, companyName: 'LogiFlow Logistics', industry: 'Logistics', stage: 'Closed Lost', stakeholders: 'VP Supply Chain (Champion), CTO (Technical), CEO (Decision)', challenges: 'Chose competitor due to existing ERP integration', outcome: 'lost' },
      { title: 'MediaGroup Ad Platform', dealValue: 150000, companyName: 'MediaGroup Agency', industry: 'Media', stage: 'Proposal', stakeholders: 'Media Director (Champion), CEO (Budget), Account Managers (Users)', challenges: 'Proving ROI over current manual processes', outcome: 'in_progress' },
      { title: 'GovTech Modernization', dealValue: 1200000, companyName: 'Federal Agency X', industry: 'Government', stage: 'RFP Response', stakeholders: 'CTO (Technical), Contracting Officer (Process), Director (Decision)', challenges: 'FedRAMP authorization, ITAR compliance', outcome: 'in_progress' },
      { title: 'InsureCo Bundle Package', dealValue: 350000, companyName: 'InsureCo Partners', industry: 'Insurance', stage: 'Closed Won', stakeholders: 'CFO (Champion), Risk Manager (User), CEO (Approver)', challenges: 'Multi-line complexity, competitive pricing pressure', outcome: 'won' },
      { title: 'StartupXYZ Growth Deal', dealValue: 48000, companyName: 'StartupXYZ', industry: 'Technology', stage: 'Closed Won', stakeholders: 'CEO (Decision Maker), VP Product (User), CTO (Technical)', challenges: 'Limited budget, fast decision needed', outcome: 'won' },
      { title: 'PharmaCo Sales Platform', dealValue: 560000, companyName: 'PharmaCo Global', industry: 'Healthcare', stage: 'Evaluation', stakeholders: 'VP Sales (Champion), IT Director (Technical), Compliance (Gatekeeper)', challenges: 'Pharma regulations, global deployment', outcome: 'in_progress' },
      { title: 'RealtyPro CRM Migration', dealValue: 95000, companyName: 'RealtyPro Network', industry: 'Real Estate', stage: 'Closed Lost', stakeholders: 'Broker (Champion), Agents (Users), Office Manager (Admin)', challenges: 'Agent adoption resistance, data migration complexity', outcome: 'lost' },
      { title: 'EnergyTech IoT Contract', dealValue: 680000, companyName: 'EnergyTech Solutions', industry: 'Energy', stage: 'Negotiation', stakeholders: 'VP Operations (Champion), CTO (Technical), CFO (Budget)', challenges: 'Remote site connectivity, harsh environment requirements', outcome: 'in_progress' }
    ]);

    // 12. Buyer Personas (15)
    await BuyerPersona.bulkCreate([
      { name: 'Technical Tim', title: 'CTO', company: 'Mid-Market SaaS', industry: 'Technology', painPoints: 'Technical debt, scaling challenges, talent retention', motivations: 'Innovation, efficiency, team productivity', communicationStyle: 'Data-driven, direct, wants technical depth', decisionCriteria: 'Architecture, scalability, security, integration capabilities' },
      { name: 'Budget-Conscious Betty', title: 'CFO', company: 'Growth-Stage Startup', industry: 'Technology', painPoints: 'Cash burn rate, ROI justification, vendor consolidation', motivations: 'Cost savings, clear ROI, financial predictability', communicationStyle: 'Numbers-focused, skeptical, wants proof', decisionCriteria: 'Total cost of ownership, ROI timeline, contract flexibility' },
      { name: 'Enterprise Ella', title: 'VP Operations', company: 'Fortune 500', industry: 'Enterprise', painPoints: 'Process inefficiency, cross-department alignment, change management', motivations: 'Operational excellence, executive visibility, career advancement', communicationStyle: 'Strategic, process-oriented, values case studies', decisionCriteria: 'Enterprise support, implementation plan, reference customers' },
      { name: 'Startup Steve', title: 'CEO/Founder', company: 'Series A Startup', industry: 'Technology', painPoints: 'Limited resources, need for speed, wearing multiple hats', motivations: 'Growth, product-market fit, investor metrics', communicationStyle: 'Fast-paced, visionary, wants quick value', decisionCriteria: 'Speed to implement, flexibility, cost, growth support' },
      { name: 'Compliance Carol', title: 'Chief Compliance Officer', company: 'Financial Services Firm', industry: 'Finance', painPoints: 'Regulatory changes, audit preparation, risk exposure', motivations: 'Risk mitigation, regulatory compliance, audit readiness', communicationStyle: 'Detail-oriented, risk-averse, needs documentation', decisionCriteria: 'Compliance certifications, audit trails, data residency' },
      { name: 'Marketing Mike', title: 'CMO', company: 'Consumer Brand', industry: 'Retail', painPoints: 'Attribution challenges, campaign ROI, channel fragmentation', motivations: 'Brand growth, lead generation, marketing efficiency', communicationStyle: 'Creative, ROI-aware, values innovation', decisionCriteria: 'Integration with marketing stack, reporting, ease of use' },
      { name: 'Healthcare Helen', title: 'Hospital Administrator', company: 'Regional Hospital Network', industry: 'Healthcare', painPoints: 'Patient outcomes, staff burnout, HIPAA compliance, costs', motivations: 'Patient care improvement, operational efficiency, compliance', communicationStyle: 'Cautious, evidence-based, long decision cycles', decisionCriteria: 'HIPAA compliance, patient impact, staff adoption, ROI' },
      { name: 'Sales Leader Sam', title: 'VP Sales', company: 'B2B SaaS Company', industry: 'Technology', painPoints: 'Rep productivity, pipeline visibility, forecast accuracy', motivations: 'Quota attainment, team performance, promotion', communicationStyle: 'Results-oriented, competitive, wants quick wins', decisionCriteria: 'Ease of adoption, reporting, integration with CRM' },
      { name: 'IT Director Ian', title: 'IT Director', company: 'Mid-Market Enterprise', industry: 'Technology', painPoints: 'System integration, security, limited staff, legacy systems', motivations: 'System reliability, security posture, team efficiency', communicationStyle: 'Technical, cautious about new vendors, values support', decisionCriteria: 'API capabilities, security certifications, support SLA' },
      { name: 'Procurement Pat', title: 'Procurement Manager', company: 'Large Enterprise', industry: 'Enterprise', painPoints: 'Vendor management, cost control, contract compliance', motivations: 'Cost savings, vendor consolidation, process compliance', communicationStyle: 'Process-driven, negotiation-focused, formal', decisionCriteria: 'Pricing, contract terms, vendor stability, references' },
      { name: 'HR Hannah', title: 'CHRO', company: 'Mid-Market Company', industry: 'General', painPoints: 'Employee retention, talent acquisition, culture building', motivations: 'Employee experience, organizational development, DEI', communicationStyle: 'People-focused, empathetic, values relationships', decisionCriteria: 'Employee impact, ease of use, vendor partnership approach' },
      { name: 'Engineering Eddie', title: 'VP Engineering', company: 'Tech Startup', industry: 'Technology', painPoints: 'Developer productivity, deployment frequency, code quality', motivations: 'Engineering velocity, system reliability, team satisfaction', communicationStyle: 'Technical, opinionated, values transparency', decisionCriteria: 'Developer experience, documentation, open-source friendly' },
      { name: 'Risk Manager Rachel', title: 'Chief Risk Officer', company: 'Insurance Company', industry: 'Insurance', painPoints: 'Risk assessment accuracy, regulatory pressure, fraud detection', motivations: 'Risk reduction, compliance, data-driven decisions', communicationStyle: 'Analytical, conservative, needs extensive validation', decisionCriteria: 'Accuracy, compliance, audit capabilities, data security' },
      { name: 'Customer Success Chris', title: 'VP Customer Success', company: 'SaaS Platform', industry: 'Technology', painPoints: 'Churn rate, expansion revenue, customer health visibility', motivations: 'NRR growth, customer satisfaction, team scalability', communicationStyle: 'Collaborative, customer-centric, data-informed', decisionCriteria: 'Integration with CS tools, automation, health scoring' },
      { name: 'Executive Edward', title: 'CEO', company: 'Mid-Market Company', industry: 'General', painPoints: 'Revenue growth, market competition, operational costs', motivations: 'Growth, market leadership, shareholder value', communicationStyle: 'Strategic, time-constrained, wants executive summary', decisionCriteria: 'Business impact, competitive advantage, trusted brand' }
    ]);

    // 13. Battle Cards (15)
    await BattleCard.bulkCreate([
      { competitorName: 'Salesforce', strengths: 'Market leader, extensive ecosystem, brand recognition', weaknesses: 'Expensive, complex implementation, long deployment times', ourAdvantage: 'Faster implementation, lower TCO, AI-native platform', counterArguments: 'We deploy in weeks vs months, our AI is built-in not bolted-on, 60% lower TCO over 3 years', pricingComparison: 'SF: $150-300/user/mo vs Ours: $89/user/mo', marketShare: '23%' },
      { competitorName: 'HubSpot', strengths: 'Easy to use, freemium model, strong marketing tools', weaknesses: 'Limited enterprise features, basic reporting, scaling issues', ourAdvantage: 'Enterprise-grade with startup simplicity, advanced AI analytics', counterArguments: 'We scale from 5 to 5000 users seamlessly, AI coaching is unique to our platform', pricingComparison: 'HS: $50-120/user/mo vs Ours: $89/user/mo', marketShare: '12%' },
      { competitorName: 'Gong', strengths: 'Conversation intelligence leader, strong call recording', weaknesses: 'Expensive, limited to call analysis, no coaching automation', ourAdvantage: 'Full platform vs point solution, AI coaching + practice + analytics', counterArguments: 'Why pay for just call recording when you can get a complete training platform?', pricingComparison: 'Gong: $100-150/user/mo vs Ours: $89/user/mo', marketShare: '8%' },
      { competitorName: 'Outreach', strengths: 'Strong sequencing, large customer base, good integrations', weaknesses: 'Steep learning curve, limited AI, expensive add-ons', ourAdvantage: 'Integrated AI coaching, simpler UX, all-inclusive pricing', counterArguments: 'Our platform includes what Outreach charges extra for, plus AI-powered training', pricingComparison: 'Outreach: $100-130/user/mo vs Ours: $89/user/mo', marketShare: '10%' },
      { competitorName: 'Chorus (ZoomInfo)', strengths: 'Bundled with ZoomInfo data, conversation analytics', weaknesses: 'Forced bundling, limited standalone value, integration issues', ourAdvantage: 'Standalone value, open integrations, comprehensive training features', counterArguments: 'You should not have to buy a data package to get conversation intelligence', pricingComparison: 'Chorus: Bundled $200+/user/mo vs Ours: $89/user/mo', marketShare: '6%' },
      { competitorName: 'Mindtickle', strengths: 'Strong content management, readiness index, enterprise focus', weaknesses: 'Complex setup, expensive, limited AI simulation', ourAdvantage: 'AI-powered role-play that Mindtickle cannot match, faster time to value', counterArguments: 'Our AI simulations provide unlimited practice scenarios vs static content', pricingComparison: 'MT: $15-40/user/mo vs Ours: $89/user/mo (more features)', marketShare: '4%' },
      { competitorName: 'Seismic', strengths: 'Content management leader, strong enterprise presence', weaknesses: 'Content-focused only, no AI training, high price point', ourAdvantage: 'Complete training platform with content AND AI coaching', counterArguments: 'Content without training is like a library without teachers', pricingComparison: 'Seismic: $40-80/user/mo vs Ours: $89/user/mo', marketShare: '5%' },
      { competitorName: 'Lessonly (Seismic)', strengths: 'Simple course creation, good UX for small teams', weaknesses: 'Limited AI, basic analytics, no simulation capabilities', ourAdvantage: 'AI-powered simulations and real-time coaching vs static lessons', counterArguments: 'Static training has 10% retention. Our AI role-plays achieve 85% skill retention', pricingComparison: 'Lessonly: $25-50/user/mo vs Ours: $89/user/mo', marketShare: '3%' },
      { competitorName: 'Brainshark', strengths: 'Video coaching, content authoring, established brand', weaknesses: 'Outdated UI, limited AI, no real-time coaching', ourAdvantage: 'Modern AI platform with real-time feedback vs recorded video review', counterArguments: 'Why wait days for manager review when AI gives instant feedback?', pricingComparison: 'Brainshark: $30-60/user/mo vs Ours: $89/user/mo', marketShare: '3%' },
      { competitorName: 'Allego', strengths: 'Video learning, mobile-friendly, conversation intelligence', weaknesses: 'Limited AI coaching, small ecosystem, niche market', ourAdvantage: 'Comprehensive AI training platform vs video-centric tool', counterArguments: 'Video is one modality. Our platform covers simulation, coaching, and analytics', pricingComparison: 'Allego: $50-100/user/mo vs Ours: $89/user/mo', marketShare: '2%' },
      { competitorName: 'SalesLoft', strengths: 'Strong cadence management, good Salesforce integration', weaknesses: 'Limited training features, no AI coaching, engagement only', ourAdvantage: 'Complete sales training + enablement vs just engagement', counterArguments: 'Engagement without training is like running without stretching - unsustainable', pricingComparison: 'SL: $75-125/user/mo vs Ours: $89/user/mo', marketShare: '7%' },
      { competitorName: 'Highspot', strengths: 'Content management, analytics, Salesforce integration', weaknesses: 'No AI training, limited coaching, content-centric only', ourAdvantage: 'AI-powered training and coaching that Highspot lacks', counterArguments: 'The best content is useless if reps cannot practice delivering it', pricingComparison: 'Highspot: $40-75/user/mo vs Ours: $89/user/mo', marketShare: '4%' },
      { competitorName: 'Showpad', strengths: 'Content management, easy sharing, good mobile app', weaknesses: 'Weak analytics, no AI, limited training capabilities', ourAdvantage: 'AI-driven training and analytics that Showpad cannot provide', counterArguments: 'Sharing content is step 1. We help reps master how to use it effectively', pricingComparison: 'Showpad: $35-65/user/mo vs Ours: $89/user/mo', marketShare: '3%' },
      { competitorName: 'Revenue.io', strengths: 'Real-time call guidance, good analytics', weaknesses: 'Call-only focus, expensive, limited simulation', ourAdvantage: 'Full training lifecycle vs call-moment-only support', counterArguments: 'Real-time guidance helps in the moment, but our platform builds lasting skills', pricingComparison: 'Revenue.io: $85-150/user/mo vs Ours: $89/user/mo', marketShare: '2%' },
      { competitorName: 'Second Nature AI', strengths: 'AI role-play focused, good simulation quality', weaknesses: 'Limited to role-play only, no analytics platform, small team', ourAdvantage: 'Complete platform with role-play AND analytics, coaching, playbooks', counterArguments: 'Why buy a point solution when our platform includes world-class AI simulation plus everything else?', pricingComparison: 'SN: $50-100/user/mo vs Ours: $89/user/mo', marketShare: '1%' }
    ]);

    // 14. Training Modules (15)
    await TrainingModule.bulkCreate([
      { title: 'Sales Fundamentals 101', description: 'Core selling skills every rep needs to master', category: 'Fundamentals', content: 'Topics: Building rapport, Active listening, Questioning techniques, Value proposition delivery, Basic objection handling', duration: 120, difficulty: 'beginner', completionRate: 95, status: 'active' },
      { title: 'SPIN Selling Methodology', description: 'Master the SPIN questioning framework', category: 'Methodology', content: 'Situation questions, Problem questions, Implication questions, Need-payoff questions, Practice exercises', duration: 90, difficulty: 'intermediate', completionRate: 78, status: 'active' },
      { title: 'Challenger Sale Approach', description: 'Learn to teach, tailor, and take control', category: 'Methodology', content: 'Commercial teaching, Tailoring messages, Taking control of the sale, Constructive tension, Reframe exercises', duration: 90, difficulty: 'advanced', completionRate: 65, status: 'active' },
      { title: 'Discovery Call Mastery', description: 'Run effective discovery calls that qualify and convert', category: 'Skills', content: 'Pre-call research, Opening techniques, Pain discovery, Budget qualification, Next step commitment', duration: 60, difficulty: 'intermediate', completionRate: 82, status: 'active' },
      { title: 'Objection Handling Workshop', description: 'Handle any objection with confidence', category: 'Skills', content: 'LAER framework, Common objection patterns, Role-play exercises, Real-world scenarios, Confidence building', duration: 75, difficulty: 'intermediate', completionRate: 88, status: 'active' },
      { title: 'Enterprise Selling', description: 'Navigate complex enterprise sales cycles', category: 'Advanced', content: 'Stakeholder mapping, Multi-threading, MEDDPICC, Executive presentations, Complex deal management', duration: 180, difficulty: 'advanced', completionRate: 55, status: 'active' },
      { title: 'Negotiation Mastery', description: 'Advanced negotiation techniques for sales', category: 'Skills', content: 'BATNA framework, Anchoring, Concession trading, Win-win strategies, Contract negotiation', duration: 90, difficulty: 'advanced', completionRate: 62, status: 'active' },
      { title: 'Social Selling on LinkedIn', description: 'Leverage LinkedIn for pipeline generation', category: 'Prospecting', content: 'Profile optimization, Content strategy, Engagement tactics, InMail templates, SSI improvement', duration: 45, difficulty: 'beginner', completionRate: 91, status: 'active' },
      { title: 'Product Demo Excellence', description: 'Deliver compelling product demonstrations', category: 'Skills', content: 'Demo preparation, Storytelling framework, Feature-benefit mapping, Handling live questions, Follow-up strategy', duration: 60, difficulty: 'intermediate', completionRate: 76, status: 'active' },
      { title: 'Pipeline Management', description: 'Build and manage a healthy sales pipeline', category: 'Process', content: 'Pipeline math, Stage definitions, Forecast methodology, Pipeline hygiene, CRM best practices', duration: 60, difficulty: 'beginner', completionRate: 85, status: 'active' },
      { title: 'Cold Calling Bootcamp', description: 'Master the art and science of cold calling', category: 'Prospecting', content: 'Opening lines, Gatekeeper navigation, Pattern interrupts, Voicemail strategy, Call blocks', duration: 90, difficulty: 'beginner', completionRate: 72, status: 'active' },
      { title: 'Email Copywriting for Sales', description: 'Write emails that get responses', category: 'Prospecting', content: 'Subject line optimization, Personalization at scale, CTA best practices, A/B testing, Sequence design', duration: 45, difficulty: 'intermediate', completionRate: 80, status: 'active' },
      { title: 'Closing Techniques', description: 'Learn proven closing strategies', category: 'Skills', content: 'Trial close, Assumptive close, Summary close, Urgency techniques, Mutual action plans', duration: 75, difficulty: 'intermediate', completionRate: 70, status: 'active' },
      { title: 'Account-Based Selling', description: 'Strategic approach to target accounts', category: 'Advanced', content: 'Account selection, Research methodology, Personalized outreach, Multi-channel strategy, Account planning', duration: 120, difficulty: 'advanced', completionRate: 58, status: 'active' },
      { title: 'Sales Analytics & Metrics', description: 'Data-driven selling and performance tracking', category: 'Process', content: 'Key metrics, Dashboard creation, Trend analysis, A/B testing, Data-driven coaching', duration: 60, difficulty: 'intermediate', completionRate: 74, status: 'active' }
    ]);

    // 15. Negotiation Tactics (15)
    await NegotiationTactic.bulkCreate([
      { name: 'Anchoring', description: 'Set the initial reference point high to frame the negotiation', category: 'Opening', whenToUse: 'At the start of pricing discussions. Present your premium package first.', example: 'Our enterprise package is $200K/year and includes everything. For your specific needs, I can also show our growth tier at $120K.', effectiveness: 'high', riskLevel: 'low' },
      { name: 'BATNA Leverage', description: 'Know your Best Alternative To Negotiated Agreement', category: 'Preparation', whenToUse: 'When you have strong alternatives and the prospect is pushing hard on price.', example: 'We have significant demand for our platform. While we want to work with you, we cannot go below our standard enterprise pricing.', effectiveness: 'high', riskLevel: 'medium' },
      { name: 'Nibbling', description: 'Ask for small concessions after main terms are agreed', category: 'Closing', whenToUse: 'After the main deal terms are essentially agreed upon.', example: 'Great, we are aligned on pricing. Could we also include early payment terms of net-15 instead of net-30?', effectiveness: 'medium', riskLevel: 'low' },
      { name: 'Bracketing', description: 'If the final price will be in the middle, start at double the distance', category: 'Pricing', whenToUse: 'When you expect the prospect to negotiate to a midpoint.', example: 'If target is $100K and prospect offers $70K, counter at $130K. The midpoint is $100K.', effectiveness: 'medium', riskLevel: 'medium' },
      { name: 'Trading Concessions', description: 'Never give something for nothing - always trade', category: 'Core', whenToUse: 'Any time the prospect asks for a discount or concession.', example: 'I can offer a 10% discount if you commit to a 2-year term instead of annual. This protects both of us.', effectiveness: 'high', riskLevel: 'low' },
      { name: 'The Flinch', description: 'React visibly to an unreasonable request to reset expectations', category: 'Tactical', whenToUse: 'When the prospect makes an extreme request or demand.', example: 'A 50% discount? [pause] That is significantly below what any of our enterprise customers pay. Help me understand what is driving that number.', effectiveness: 'medium', riskLevel: 'medium' },
      { name: 'Good Cop / Bad Cop', description: 'Use team dynamics to create negotiation flexibility', category: 'Team', whenToUse: 'In team selling situations where you can play different roles.', example: 'I would love to make that work. Let me check with my VP of Sales - she is very strict on pricing, but I will advocate for you.', effectiveness: 'medium', riskLevel: 'high' },
      { name: 'Deadline Pressure', description: 'Create genuine urgency with time-limited offers', category: 'Closing', whenToUse: 'When the deal is stalling and you need to create momentum.', example: 'Our Q1 pricing includes implementation at no cost. After March 31st, that is a $25K addition. I want to make sure you get the best deal.', effectiveness: 'high', riskLevel: 'medium' },
      { name: 'The Walk Away', description: 'Be willing to walk away from a bad deal', category: 'Power', whenToUse: 'When negotiations reach an impasse and terms are below your floor.', example: 'I appreciate the conversation, but at those terms we cannot deliver the quality you deserve. If circumstances change, we would love to revisit.', effectiveness: 'high', riskLevel: 'high' },
      { name: 'Silence', description: 'Use strategic pauses to let the other party fill the gap', category: 'Tactical', whenToUse: 'After making a proposal or asking a key question.', example: 'Our investment for this solution is $150,000. [silence - wait for their response, do not speak first]', effectiveness: 'high', riskLevel: 'low' },
      { name: 'Decoy Option', description: 'Present three options where one is clearly the best value', category: 'Pricing', whenToUse: 'During pricing presentations to guide the prospect to your preferred option.', example: 'Option A: Basic at $50K (limited). Option B: Professional at $100K (recommended - best value). Option C: Enterprise at $180K (premium).', effectiveness: 'high', riskLevel: 'low' },
      { name: 'Splitting the Difference', description: 'Propose meeting in the middle as a fair compromise', category: 'Closing', whenToUse: 'When both parties are close to agreement but a gap remains.', example: 'We are at $120K and you are at $100K. How about we meet at $110K with the extended support package included?', effectiveness: 'medium', riskLevel: 'low' },
      { name: 'Future Value Promise', description: 'Offer future benefits instead of immediate discounts', category: 'Creative', whenToUse: 'When the prospect wants a discount but you need to protect current pricing.', example: 'Instead of a discount now, how about we guarantee your renewal rate for 3 years? That protects you from any future increases.', effectiveness: 'medium', riskLevel: 'low' },
      { name: 'Cherry Picking Prevention', description: 'Protect your pricing from being unbundled', category: 'Defense', whenToUse: 'When the prospect tries to cherry-pick individual features at lower prices.', example: 'Our platform is designed as an integrated solution. The AI coaching relies on the analytics data, so they work best together at the package price.', effectiveness: 'medium', riskLevel: 'medium' },
      { name: 'Reciprocity Trigger', description: 'Give something of value first to create obligation', category: 'Relationship', whenToUse: 'Early in the relationship to build goodwill and trust.', example: 'Before we discuss pricing, I put together a custom industry benchmark report for [Company]. It shows where you stand vs peers. [Give value first]', effectiveness: 'high', riskLevel: 'low' }
    ]);

    // 16. Leaderboard (15)
    await LeaderboardEntry.bulkCreate([
      { userId: 1, userName: 'John Mitchell', totalScore: 945, sessionsCompleted: 28, winRate: 72.5, rank: 1, badge: 'Diamond', period: 'March 2024' },
      { userId: 3, userName: 'Mike Johnson', totalScore: 912, sessionsCompleted: 25, winRate: 68.0, rank: 2, badge: 'Platinum', period: 'March 2024' },
      { userId: 2, userName: 'Sarah Chen', totalScore: 887, sessionsCompleted: 22, winRate: 65.5, rank: 3, badge: 'Platinum', period: 'March 2024' },
      { userId: 4, userName: 'Emily Davis', totalScore: 854, sessionsCompleted: 20, winRate: 62.0, rank: 4, badge: 'Gold', period: 'March 2024' },
      { userId: 1, userName: 'John Mitchell', totalScore: 1850, sessionsCompleted: 55, winRate: 71.0, rank: 1, badge: 'Diamond', period: 'Q1 2024' },
      { userId: 2, userName: 'Sarah Chen', totalScore: 1720, sessionsCompleted: 48, winRate: 66.0, rank: 2, badge: 'Platinum', period: 'Q1 2024' },
      { userId: 3, userName: 'Mike Johnson', totalScore: 1680, sessionsCompleted: 45, winRate: 64.5, rank: 3, badge: 'Platinum', period: 'Q1 2024' },
      { userId: 4, userName: 'Emily Davis', totalScore: 1590, sessionsCompleted: 42, winRate: 60.0, rank: 4, badge: 'Gold', period: 'Q1 2024' },
      { userId: 1, userName: 'John Mitchell', totalScore: 920, sessionsCompleted: 26, winRate: 70.0, rank: 1, badge: 'Diamond', period: 'February 2024' },
      { userId: 2, userName: 'Sarah Chen', totalScore: 890, sessionsCompleted: 24, winRate: 67.0, rank: 2, badge: 'Platinum', period: 'February 2024' },
      { userId: 4, userName: 'Emily Davis', totalScore: 860, sessionsCompleted: 21, winRate: 63.0, rank: 3, badge: 'Gold', period: 'February 2024' },
      { userId: 3, userName: 'Mike Johnson', totalScore: 845, sessionsCompleted: 20, winRate: 61.5, rank: 4, badge: 'Gold', period: 'February 2024' },
      { userId: 1, userName: 'John Mitchell', totalScore: 880, sessionsCompleted: 24, winRate: 69.0, rank: 1, badge: 'Platinum', period: 'January 2024' },
      { userId: 3, userName: 'Mike Johnson', totalScore: 850, sessionsCompleted: 22, winRate: 65.0, rank: 2, badge: 'Gold', period: 'January 2024' },
      { userId: 2, userName: 'Sarah Chen', totalScore: 830, sessionsCompleted: 20, winRate: 63.5, rank: 3, badge: 'Gold', period: 'January 2024' }
    ]);

    console.log('All seed data inserted successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Seed error:', error);
    process.exit(1);
  }
}

seed();
